services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  producer:
    build:
      context: .
      dockerfile: docker/producer.Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092

  ml_service:
    build:
      context: .
      dockerfile: docker/ml_service.Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - "5002:5000"

  alert_service:
    build:
      context: .
      dockerfile: docker/alert_service.Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - "5001:5001"

  web_ui:
    build:
      context: .
      dockerfile: docker/web_ui.Dockerfile
    ports:
      - "8000:8000"   # ONLY expose UI
    depends_on:
      - ml_service
      - alert_service

  spark:
    build:
      context: .
      dockerfile: docker/spark.Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - ML_SERVICE_URL=http://ml_service:5002/predict
      - ALERT_SERVICE_URL=http://alert_service:5001/alert
