apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-alert-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-alert-service
  template:
    metadata:
      labels:
        app: fraud-alert-service
    spec:
      containers:
      - name: fraud-alert-service
        image: honey254/fraud-alert-service:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        ports:
        - containerPort: 5001
