apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-web-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-web-ui
  template:
    metadata:
      labels:
        app: fraud-web-ui
    spec:
      containers:
      - name: fraud-web-ui
        image: honey254/fraud-web-ui:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        ports:
        - containerPort: 8000
